### ISSUE TITLE
Weird behaviour with array of objects as input

### ISSUE THREAD

**Issue by dhautotlf** [sindresorhus/camelcase-keys#13]
```
camelcaseKeys([{'foo-bar': true}], {deep:true})
```
gives
```
{
    0: {
        fooBar: true
    }
}
```
I was expecting 
```
[
    {
        fooBar: true
    }
]
```
Since
```
camelcaseKeys({'test': [{'foo-bar': [{'foo-baz': true}]}]}, {deep:true});
```
Gives
```
{
    test: [
        {
            fooBar: [{ fooBaz }]
        }
    ]
}
```

**Comment by sindresorhus** [comment]
I'm not sure why you were expecting that. The documentation clearly states it accepts an `Object` only.

**Comment by dhautotlf** [comment]
When using a string for instance, an error is thrown. Maybe it should be the case for Arrays.

**Comment by jbrantly** [comment]
Is there any reason that it couldn't accept an array, or at least accept it when `deep` is true? Clearly the logic is already there for iterating arrays at lower levels.

In my use-case at least I'm transforming PascalCased JSON service responses into camelCased responses. It would be convenient if I could use this library without having to distinguish between Objects and Arrays since in both cases I'm just trying to change the keys of the entire object graph.

**Comment by dhautotlf** [comment]
@jbrantly to solve this, I'm wrapping the array in an object and it work.
But I didn't see the issue at the first sight and it is a bit confusing imo.

**Comment by kevva** [comment]
Why aren't you just mapping the `Array` like:

```js
[{'foo-bar': true}, {'foo-bar': true}].map(x => camelCaseKeys(x));
//=> [{fooBar: true}, {fooBar: true}]
```

**Comment by Richtermeister** [comment]
My little work-around has been:
```
let isArray = Array.isArray(data)
data = camelcaseKeys(data, {deep: true})
if (isArray) {
    data = Object.keys(data).map(key => data[key])
}
```
Works as expected, but seems simple enough to just tuck into the library, unless there's an issue I'm not seeing..
