### ISSUE TITLE
Option 'deep' does nothing in 6.2.1

### ISSUE THREAD

**Issue by lami02** [sindresorhus/camelcase-keys#57]
Hi,
in release 6.2.1 the Option 'deep' does nothing.

`camelcaseKeys({a_b: {c_d: 1}}, {deep:true})`
`//=> {aB: {c_d: 1}}`

I tested 6.1.2 and in that release everything was fine.

**Comment by sindresorhus** [comment]
There were no actual JS changes between those versions: https://github.com/sindresorhus/camelcase-keys/compare/v6.1.2...v6.2.1

**Comment by russcarver** [comment]
Same issue in 6.2.2. Downgrading to 6.1.2 solved it. Please fix.

**Comment by aguynamedben** [comment]
FWIW I thought this was happening to me, but after adding some console.log's directly after camelizeKeys is called, I realized the cause was a poorly implemented redux action that was dropping the update based on a matching uuid. I have synced to redux without `{ deep: true }` present, and subsequent syncs with `{ deep: true }` were being incorrectly dropped by my redux action.

![image](https://user-images.githubusercontent.com/107841/104995891-d3bcae80-59db-11eb-9ced-2428ec9e3afb.png)

`{ deep: true }` on 6.2.2 works as expected for me. Thanks for all the work you do 🙏 I love that I found this library, and the other ones you manage.
